name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write  # リリース作成に必要な権限を追加

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-latest
            name: macOS
            ext: .app
          - os: windows-latest
            name: Windows
            ext: .exe
          - os: ubuntu-latest
            name: Linux
            ext: ''
      fail-fast: false
            
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pandas reportlab
        
    - name: List Python files (Unix)
      if: runner.os != 'Windows'
      run: |
        echo "Python files in directory:"
        ls *.py 2>/dev/null || echo "No Python files found"
        
    - name: List Python files (Windows)
      if: runner.os == 'Windows'
      shell: cmd
      run: |
        echo Python files in directory:
        dir *.py 2>NUL || echo No Python files found
        
    - name: Build executable (Unix)
      if: runner.os != 'Windows'
      run: |
        for file in *.py; do
          if [ -f "$file" ]; then
            echo "Building with $file"
            pyinstaller --onefile --windowed --name PDFGenerator "$file"
            break
          fi
        done
        
    - name: Build executable (Windows)
      if: runner.os == 'Windows'
      shell: powershell
      run: |
        $pyfile = Get-ChildItem -Filter *.py | Select-Object -First 1
        if ($pyfile) {
          Write-Host "Building with $($pyfile.Name)"
          pyinstaller --onefile --windowed --name PDFGenerator $pyfile.Name
        } else {
          Write-Host "No Python files found"
          exit 1
        }
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: PDFGenerator-${{ matrix.name }}
        path: dist/*
        
  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write  # リリース作成権限
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          PDFGenerator-*/*
        draft: false
        prerelease: false
        generate_release_notes: true
