name: Build Executables

on:
  push:
    tags:
      - 'v*'  # v1.0.0のようなタグがプッシュされたときに実行

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pandas reportlab
        
    - name: Build executable
      run: |
        pyinstaller --onefile --windowed --name PDFGenerator your_script.py
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: PDFGenerator-${{ matrix.os }}
        path: dist/*
        
  release:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Download all artifacts
      uses: actions/download-artifact@v3
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          PDFGenerator-windows-latest/*
          PDFGenerator-macos-latest/*
          PDFGenerator-ubuntu-latest/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}