name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:  # 手動実行も可能にする

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-latest
            name: macOS
            ext: .app
          - os: windows-latest
            name: Windows
            ext: .exe
          - os: ubuntu-latest
            name: Linux
            ext: ''
            
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pandas reportlab
        
    - name: Build executable
      run: |
        pyinstaller --onefile --windowed --name PDFGenerator *.py
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: PDFGenerator-${{ matrix.name }}
        path: dist/*
        
  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Download all artifacts
      uses: actions/download-artifact@v3
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          PDFGenerator-*/*
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
